### ISSUE TITLE
Image for biome T6 was overwriten

### ISSUE THREAD

**Issue by jrfep** [red-list-ecosystem/typology-map-content#10]
The image for biome T6 was overwritten with the image from T7:

assets/uploads/t_6.jpg

**Comment by jrfep** [comment]
@dmprk could you please check this, I think this got overwritten in the last upload

**Comment by tmfrnz** [comment]
well spotted! the spreadsheet has now a link to the correct image, so we will update this in due course

**Comment by tmfrnz** [comment]
this has been updated as part of https://github.com/red-list-ecosystem/typology-map-content/commit/eed1638d4d02e9acc416288c967536773e23ff2f#diff-b2e2a70aef347b582c38544744f7f948

image: https://github.com/red-list-ecosystem/typology-map-content/blob/eed1638d4d02e9acc416288c967536773e23ff2f/assets/uploads/t_6.jpg
