### ISSUE TITLE
Check images for subterranean transitional biomes

### ISSUE THREAD

**Issue by jrfep** [red-list-ecosystem/typology-map-content#11]
The foto for group [SF2.2](assets/uploads/sf_2_2.jpg) was overwritten by the foto of biome [SM1](assets/uploads/sm_1.jpg).

**Comment by tmfrnz** [comment]
@dmprk: i think it should be https://www.dropbox.com/s/xhe92verwv8tslk/image154.jpeg?dl=0

**Comment by jrfep** [comment]
Yes, that is the right one for SF2.2
