### ISSUE TITLE
Greater equal symbol

### ISSUE THREAD

**Issue by jrfep** [red-list-ecosystem/typology-map-content#12]
How do we display a greater-equal  symbol?
In https://global-ecosystems.org/explore/groups/F3.1 under distribution it should be "&geq; 50 km2".
I tried with `&geq;`  but it does not get properly translated.

**Comment by tmfrnz** [comment]
You should be able to just paste the symbol "≥"
https://github.com/red-list-ecosystem/typology-map-content/commit/07f1097acc5ff279491eb97c15ad49308f310c92

At least for me this appears to be working.
